name: Release
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DB_TASK_SECURITY_GROUPS: ${{ secrets.DB_TASK_SECURITY_GROUPS }}
      DB_TASK_SUBNETS: ${{ secrets.DB_TASK_SUBNETS }}

    steps:
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1

      - name: Release
        env:
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}
          REACT_APP_SENTRY_RELEASE: ${{ steps.vars.outputs.sha_short }}
        run: ./scripts/release.sh
